In [1]:
import numpy as np
arr=np.arange(10)
print(arr)
np.save('some_array',arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
np.load('some_array.npy')


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.savez('array_archieve.npz',a=arr,b=arr)

In [4]:
arch=np.load('array_archieve.npz')

In [5]:
arch['b']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
from numpy.linalg import inv,qr

In [12]:
X=randn(5,5)

NameError: name 'randn' is not defined

In [ ]:
mat=X.T.dot(X)

In [ ]:
inv(mat)

In [ ]:
mat.dot(inv(mat))